---
title: "Next steps"
author: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  NinaR::jensAnalysis:
    highlight: tango
    fig_caption: yes
    toc: yes
---


## Simulate landscape patterns

- Implement function to calculate distance through GRASS

- Implement function to calculate density through GRASS, using r.mfilter and r.resamp.filter

- Implement exp decay distance - OK!

- Calculate distance between points - OK!

- Allow calc_dist to calculate distance for multiple parameters  
(different methods or different parameters for exp)

- Set a reasonable set of landscapes to tell a history: from random to clustered, plus regular 
  - v1. normal dist vs density;
  - v2. dist for all features, exp_decay dist, then min and sum;
  - v3. exp_decay dist vs exp_decay filter
  
- Simulate points and check correlation

- See best form to represent this (using dist_points, or ZOI, or what)

## Re-do analysis for reindeer GPS points



Notes

- We only do simulations for point infrastructure; it is harder to simulate real case scenarios for
lines and polygons, but the insights from the point scenarios should hold true for these other cases.