---
title: "Next steps: cumulative influence manuscript"
author: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  NinaR::jensAnalysis:
    highlight: tango
    fig_caption: yes
    toc: yes
---

1. Text:
  - Reduce text, check references and minimize them

2. Appendix A
  - Complete Appendix with derivation for lines and polygons
  - Mention correspondence between sum of functions and a neighborhood analysis
3. Appendix B
  - Add text to Appendix B
  - Maybe also add results for log-dist here?
4. Appendix C
  - Fix how Fig C7 (maps) look like
  - Check why references are not working

5. Appendix D
  - Write it.
  - It should be an introduction to  demonstration of the use of functions to calculate dist and cum inf in both 
R and GRASS GIS. Explain how to download the package, which are the functions, the parameters and
options/methods, and plot some results. (This might be a vignette of the package as well)
(maybe separate results in R and GRASS in two different appendices?)
6. Maybe another appendix explaining the possible influence functions?


## Notes

- xx % of the studies still use only the distance to the nearest feature. Many other (yy%) also
use densities or spatial filters derived from the variables, with the main purpose of
analyzing the scale of effect / ZoI of the infrastructure of variable (and possibly the joint
effect at multiple scales). Here we present an additional reason for using desnity-related
measures, which is the possibility to represent the cumulative influence of same-type 
infrastructure in space.

- We only do simulations for point infrastructure; it is harder to simulate real case scenarios for
lines and polygons, but the insights from the point scenarios should hold true for these other cases.

- Maybe instead of saying that one measure is better than the other, the comparison distance vs
cumm effect might be used to test if the effects of multiple infrastructure of the same type 
accumulate over space or not.